spring:
  security:
    account-expiration: 3000000
    credentials-expiration: 3000000
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?stringtype=unspecified
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:migrations/changelog.xml

jwt:
  token:
    secret: testsecret123gedasgjj1242tjgewgjesfggjerdsfjgls;
    expired: 3600000